### ISSUE TITLE
Error or no output when trying to compile tags

### ISSUE THREAD

**Issue by tomspeak** [ramitos/jsctags#35]
This is what I get if I try to run the recommended command from the README:

```
tomspeak$ find . -type f -iregex .*\.js$ -exec jsctags {} -f \; | sed '/^$/d' | sort > tags
/usr/local/lib/node_modules/jsctags/node_modules/deepmerge/index.js:35
        Object.keys(src).forEach(function (key) {
               ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at deepmerge (/usr/local/lib/node_modules/jsctags/node_modules/deepmerge/index.js:35:16)
    at config (/usr/local/lib/node_modules/jsctags/src/condenser.js:34:14)
    at module.exports (/usr/local/lib/node_modules/jsctags/src/condenser.js:83:29)
    at Parser.parse (/usr/local/lib/node_modules/jsctags/src/parser.js:95:3)
    at module.exports (/usr/local/lib/node_modules/jsctags/src/parser.js:359:28)
    at /usr/local/lib/node_modules/jsctags/bin/jsctags:80:7
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

If I try to run the recommended command from #22:

```
tomspeak$ jsctags `find . -name "*.js"` -f > tags
-bash: /usr/local/bin/jsctags: Argument list too long
```

I tried to fix via #12 but that seems to be out of date as I do not have those files.

Finally,

`jsctags app.js -f` outputs nothing, no message and no tags file.

```
node: v5.0.0
npm: 3.3.6
```

Installed via: `npm install -g git+https://github.com/ramitos/jsctags.git`

Any ideas?

**Comment by eudisd** [comment]
+1

Getting similar errors

```javascript

TypeError: Object.keys called on non-object
    at Function.keys (native)
    at deepmerge (/Users/eudisduran/.nvm/versions/node/v0.12.10/lib/node_modules/jsctags/node_modules/deepmerge/index.js:35:16)
    at config (/Users/eudisduran/.nvm/versions/node/v0.12.10/lib/node_modules/jsctags/src/condenser.js:34:14)
    at module.exports (/Users/eudisduran/.nvm/versions/node/v0.12.10/lib/node_modules/jsctags/src/condenser.js:83:29)
    at Parser.parse (/Users/eudisduran/.nvm/versions/node/v0.12.10/lib/node_modules/jsctags/src/parser.js:101:3)
    at module.exports (/Users/eudisduran/.nvm/versions/node/v0.12.10/lib/node_modules/jsctags/src/parser.js:369:28)
    at /Users/eudisduran/.nvm/versions/node/v0.12.10/lib/node_modules/jsctags/bin/jsctags:80:7
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```
